telegram:
    bot1:
        token: укажите токен
        owner: укажите владельца (не обязательно)

users:
    k.bashevoy: укажите chat_id (чтобы узнать свой chat_id напишите боту любое сообщение и запустите скрипт python get_chat_id.py)
    default: 0

stickers:
    default: CAADAgADOQEAAjbsGwVonn-MGIBY3AI
    success: CAADAgADQAADyIsGAAE7MpzFPFQX5QI